name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # Executa quando há mudanças na branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Publicar no GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Publica todo o repositório

      - name: Implantar
        uses: actions/deploy-pages@v1
